apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-api-green
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-api
      version: green
  template:
    metadata:
      labels:
        app: securebank-api
        version: green
    spec:
      serviceAccountName: securebank-api   # <-- Added line
      containers:
      - name: api
        image: rajkumarvangeti/securebank-api:d2eddfd3e4e03b48dac44e1304e027e7877d928b
        ports:
        - containerPort: 8080

