apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-api-green
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-api
      version: green
  template:
    metadata:
      labels:
        app: securebank-api
        version: green
    spec:
      containers:
      - name: api
        image: rajkumarvangeti/securebank-api:6e4c4b82387d30d69ac6b0e9b9ac8f4bc07e2af1
        ports:
        - containerPort: 8080

