apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-api-blue
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-api
      version: blue
  template:
    metadata:
      labels:
        app: securebank-api
        version: blue
    spec:
      containers:
      - name: api
        image: rajkumarvangeti/securebank-api:6d92d59b9f64f2d1baa95888cc5f89c56ae91a68
        ports:
        - containerPort: 8080

