apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-api-blue
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-api
      version: blue
  template:
    metadata:
      labels:
        app: securebank-api
        version: blue
    spec:
      serviceAccountName: securebank-api   # <-- Added line
      containers:
      - name: api
        image: rajkumarvangeti/securebank-api:5ff47566e12a5caa4fc323c503c6a31cc891e0e4
        ports:
        - containerPort: 8080

