apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-api-green
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-api
      version: green
  template:
    metadata:
      labels:
        app: securebank-api
        version: green
    spec:
      containers:
      - name: api
        image: rajkumarvangeti/securebank-api:bde81330b1e39ddf25e0572e6f348ab7c8f2e36c
        ports:
        - containerPort: 8080

