apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-api
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-api
  template:
    metadata:
      labels:
        app: securebank-api
    spec:
      containers:
      - name: api
        image: rajkumarvangeti/securebank-api:1f181dfb73844cea6ad35e682d3a8101a5dbb291
        ports:
        - containerPort: 8080

