apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-api
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securebank-api
  template:
    metadata:
      labels:
        app: securebank-api
    spec:
      serviceAccountName: securebank-api   # <-- Added line
      containers:
      - name: api
        image: rajkumarvangeti/securebank-api:1870ff786f157c4eb1ee63188b540fe5a70a2882
        ports:
        - containerPort: 8080

