apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-serviceaccount
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: iamserviceaccount
    targetRevision: 0.1.0
    helm:
      values: |
        serviceAccount:
          name: securebank-api-sa
        roleArn: arn:aws:iam::<251986419131>:role/SecureBankApiRole
  destination:
    server: https://kubernetes.default.svc
    namespace: securebank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

